FISH_MAPPING = {
    "ALB": {
        "identifier": 2496,
        "scientific_name": "Thunnus alalunga",
        "name_en": "Albacore",
        "name_es": "Atún blanco",
        "name_fr": "Germon",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Albacore",
        "label2_fishnet": "ALB",
        "iucn_category": "LC",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "tuna",
    },
    "ALI": {
        "identifier": 18612,
        "scientific_name": "Alepisaurus spp",
        "name_en": "Lancetfishes nei",
        "name_es": "NA",
        "name_fr": "NA",
        "isscaap_group": "Miscellaneous coastal fishes",
        "label1_fishnet": "Lancetfish",
        "label2_fishnet": "OTH",
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "ALO": {
        "identifier": 10271,
        "scientific_name": "Alepisaurus brevirostris",
        "name_en": "Short snouted lancetfish",
        "name_es": "NA",
        "name_fr": "Lancier à nez court",
        "isscaap_group": "Miscellaneous coastal fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "ALV": {
        "identifier": 2008,
        "scientific_name": "Alopias vulpinus",
        "name_en": "Thresher",
        "name_es": "Zorro",
        "name_fr": "Renard",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "ALX": {
        "identifier": 10272,
        "scientific_name": "Alepisaurus ferox",
        "name_en": "Long snouted lancetfish",
        "name_es": "Lanzón picudo",
        "name_fr": "Lancier longnez",
        "isscaap_group": "Miscellaneous coastal fishes",
        "label1_fishnet": "Long snouted lancetfish",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "BEN": {
        "identifier": 2997,
        "scientific_name": "Belonidae",
        "name_en": "Needlefishes, etc. nei",
        "name_es": "Agujones, maraos nep",
        "name_fr": "Aiguilles, orphies nca",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "BET": {
        "identifier": 2498,
        "scientific_name": "Thunnus obesus",
        "name_en": "Bigeye tuna",
        "name_es": "Patudo",
        "name_fr": "Thon obèse(=Patudo)",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Bigeye tuna",
        "label2_fishnet": "BET",
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "tuna",
    },
    "BIL": {
        "identifier": 3300,
        "scientific_name": "Istiophoridae",
        "name_en": "Marlins,sailfishes,etc. nei",
        "name_es": "Agujas,marlines,peces vela nep",
        "name_fr": "Makaires,marlins,voiliers nca",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Marlin",
        "label2_fishnet": "BILL",
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "BIP": {
        "identifier": 3274,
        "scientific_name": "Sarda orientalis",
        "name_en": "Striped bonito",
        "name_es": "Bonito mono",
        "name_fr": "Bonite oriental",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "BLM": {
        "identifier": 2500,
        "scientific_name": "Istiompax indica",
        "name_en": "Black marlin",
        "name_es": "Aguja negra",
        "name_fr": "Makaire noir",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Black marlin",
        "label2_fishnet": "BILL",
        "iucn_category": "DD",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "marlin",
    },
    "BLR": {
        "identifier": 2019,
        "scientific_name": "Carcharhinus melanopterus",
        "name_en": "Blacktip reef shark",
        "name_es": "Tiburón de puntas negras",
        "name_fr": "Requin pointes noires",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "BRA": {
        "identifier": 18629,
        "scientific_name": "Brama spp",
        "name_en": "NA",
        "name_es": "NA",
        "name_fr": "NA",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Brama",
        "label2_fishnet": "OTH",
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "BRO": {
        "identifier": 2022,
        "scientific_name": "Carcharhinus brachyurus",
        "name_en": "Copper shark",
        "name_es": "Tiburón cobrizo",
        "name_fr": "Requin cuivre",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "BSH": {
        "identifier": 2018,
        "scientific_name": "Prionace glauca",
        "name_en": "Blue shark",
        "name_es": "Tiburón azul",
        "name_fr": "Peau bleue",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "NT",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "BTH": {
        "identifier": 2795,
        "scientific_name": "Alopias superciliosus",
        "name_en": "Bigeye thresher",
        "name_es": "Zorro ojón",
        "name_fr": "Renard à gros yeux",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": "Thresher shark",
        "label2_fishnet": "SHARK",
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "BUM": {
        "identifier": 3303,
        "scientific_name": "Makaira nigricans",
        "name_en": "Blue marlin",
        "name_es": "Aguja azul",
        "name_fr": "Makaire bleu",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Blue marlin",
        "label2_fishnet": "BILL",
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "marlin",
    },
    "BXQ": {
        "identifier": 20264,
        "scientific_name": "Makaira spp",
        "name_en": "Marlins nei",
        "name_es": "Agujas nep",
        "name_fr": "Makaires nca",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "CCE": {
        "identifier": 2812,
        "scientific_name": "Carcharhinus leucas",
        "name_en": "Bull shark",
        "name_es": "Tiburón sarda",
        "name_fr": "Requin bouledogue",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "CCG": {
        "identifier": 11130,
        "scientific_name": "Carcharhinus galapagensis",
        "name_en": "Galapagos shark",
        "name_es": "Tiburón de Galápagos",
        "name_fr": "Requin des Galapagos",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "CCR": {
        "identifier": 2020,
        "scientific_name": "Carcharhinus porosus",
        "name_en": "Smalltail shark",
        "name_es": "Tiburón poroso",
        "name_fr": "Requin tiqueue",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "CR",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "CIO": {
        "identifier": 12889,
        "scientific_name": "Isogomphodon oxyrhynchus",
        "name_en": "Daggernose shark",
        "name_es": "Cazón picudo sudamericano",
        "name_fr": "Requin bécune",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "CR",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "CUT": {
        "identifier": 3269,
        "scientific_name": "Trichiuridae",
        "name_en": "Hairtails, scabbardfishes nei",
        "name_es": "Peces sable, cintos nep",
        "name_fr": "Poissons-sabres, sabres nca",
        "isscaap_group": "Miscellaneous demersal fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "DLP": {
        "identifier": None,
        "scientific_name": "Delphinidae",
        "name_en": "Dolphins nei",
        "name_es": "Delfínidos nep",
        "name_fr": "Dauphins nca",
        "isscaap_group": "Sperm-whales, pilot-whales",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "unknown",
        "iucn_population": "unknown",
        "group": "mammal",
        "group_subcategory": "mammal",
    },
    "DOL": {
        "identifier": 3130,
        "scientific_name": "Coryphaena hippurus",
        "name_en": "Common dolphinfish",
        "name_es": "Lampuga",
        "name_fr": "Coryphène commune",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Mahi mahi",
        "label2_fishnet": "DOL",
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "fish",
        "group_subcategory": "mahi",
    },
    "DQP": {
        "identifier": 20644,
        "scientific_name": "Taractichthys spp",
        "name_en": "Pomfrets nei",
        "name_es": "NA",
        "name_fr": "NA",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Pomfret",
        "label2_fishnet": "OTH",
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "DUS": {
        "identifier": 2811,
        "scientific_name": "Carcharhinus obscurus",
        "name_en": "Dusky shark",
        "name_es": "Tiburón arenero",
        "name_fr": "Requin de sable",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "FAL": {
        "identifier": 2021,
        "scientific_name": "Carcharhinus falciformis",
        "name_en": "Silky shark",
        "name_es": "Tiburón jaquetón",
        "name_fr": "Requin soyeux",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-silky",
    },
    "FRZ": {
        "identifier": 3292,
        "scientific_name": "Auxis thazard, A. rochei",
        "name_en": "Frigate and bullet tunas",
        "name_es": "Melva y melvera",
        "name_fr": "Auxide et bonitou",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "GBA": {
        "identifier": 3048,
        "scientific_name": "Sphyraena barracuda",
        "name_en": "Great barracuda",
        "name_es": "Picuda barracuda",
        "name_fr": "Barracuda",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Great barracuda",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "GEM": {
        "identifier": 3268,
        "scientific_name": "Rexea solandri",
        "name_en": "Silver gemfish",
        "name_es": "Escolar plateado",
        "name_fr": "Escolier tifiati",
        "isscaap_group": "Miscellaneous demersal fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "GES": {
        "identifier": 12302,
        "scientific_name": "Gempylus serpens",
        "name_en": "Snake mackerel",
        "name_es": "Escolar de canal",
        "name_fr": "Escolier serpent",
        "isscaap_group": "Miscellaneous demersal fishes",
        "label1_fishnet": "Snake mackerel",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "HEM": {
        "identifier": 12658,
        "scientific_name": "Heterodontus mexicanus",
        "name_en": "Mexican hornshark",
        "name_es": "Dormilón búfalo",
        "name_fr": "Requin dormeur buffle",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "KAW": {
        "identifier": 3294,
        "scientific_name": "Euthynnus affinis",
        "name_en": "Kawakawa",
        "name_es": "Bacoreta oriental",
        "name_fr": "Thonine orientale",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "LAG": {
        "identifier": 2247,
        "scientific_name": "Lampris guttatus",
        "name_en": "Opah",
        "name_es": "Opa",
        "name_fr": "Opah",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Opah",
        "label2_fishnet": "LAG",
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "LEC": {
        "identifier": 3267,
        "scientific_name": "Lepidocybium flavobrunneum",
        "name_en": "Escolar",
        "name_es": "Escolar negro",
        "name_fr": "Escolier noir",
        "isscaap_group": "Miscellaneous demersal fishes",
        "label1_fishnet": "Escolar",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "LMA": {
        "identifier": 2797,
        "scientific_name": "Isurus paucus",
        "name_en": "Longfin mako",
        "name_es": "Marrajo carite",
        "name_fr": "Petite taupe",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "LOZ": {
        "identifier": 19100,
        "scientific_name": "Lobotes pacificus",
        "name_en": "Pacific tripletail",
        "name_es": "Dormilona del Pacífico",
        "name_fr": "Croupia roche du Pacifique",
        "isscaap_group": "Miscellaneous demersal fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "MAN": {
        "identifier": 2063,
        "scientific_name": "Mobulidae",
        "name_en": "Mantas, devil rays nei",
        "name_es": "Mantas, diablos nep",
        "name_fr": "Mantes, diables de mer nca",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "ray",
        "group_subcategory": "ray",
    },
    "MLS": {
        "identifier": 2501,
        "scientific_name": "Kajikia audax",
        "name_en": "Striped marlin",
        "name_es": "Marlín rayado",
        "name_fr": "Marlin rayé",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Striped marlin",
        "label2_fishnet": "BILL",
        "iucn_category": "LC",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "marlin",
    },
    "MRW": {
        "identifier": 13380,
        "scientific_name": "Masturus lanceolatus",
        "name_en": "Sharptail mola",
        "name_es": None,
        "name_fr": "Poisson-lune lancéolé",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "MUU": {
        "identifier": 13563,
        "scientific_name": "Mustelus lunulatus",
        "name_en": "Sicklefin smooth-hound",
        "name_es": "Musola segadora",
        "name_fr": "Émissole mamon",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "NGB": {
        "identifier": 2026,
        "scientific_name": "Negaprion brevirostris",
        "name_en": "Lemon shark",
        "name_es": "Tiburón galano",
        "name_fr": "Requin citron",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "OIL": {
        "identifier": 2467,
        "scientific_name": "Ruvettus pretiosus",
        "name_en": "Oilfish",
        "name_es": "Escolar clavo",
        "name_fr": "Rouvet",
        "isscaap_group": "Miscellaneous demersal fishes",
        "label1_fishnet": "Oilfish",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "PLS": {
        "identifier": 2062,
        "scientific_name": "Pteroplatytrygon violacea",
        "name_en": "Pelagic stingray",
        "name_es": "Raya-látigo violeta",
        "name_fr": "Pastenague violette",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": "Pelagic stingray",
        "label2_fishnet": "PLS",
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "ray",
        "group_subcategory": "ray",
    },
    "PSK": {
        "identifier": 14647,
        "scientific_name": "Pseudocarcharias kamoharai",
        "name_en": "Crocodile shark",
        "name_es": "Tiburón cocodrilo",
        "name_fr": "Requin crocodile",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "increasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "PTH": {
        "identifier": 2009,
        "scientific_name": "Alopias pelagicus",
        "name_en": "Pelagic thresher",
        "name_es": "Zorro pelágico",
        "name_fr": "Renard pélagique",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "REM": {
        "identifier": 18619,
        "scientific_name": "Remora spp",
        "name_en": "Shark suckers",
        "name_es": "NA",
        "name_fr": "NA",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "REZ": {
        "identifier": 19400,
        "scientific_name": "Remora osteochir",
        "name_en": "Marlin sucker",
        "name_es": "Agarrador",
        "name_fr": "Rémora des marlins",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "RMV": {
        "identifier": 18767,
        "scientific_name": "Mobula spp",
        "name_en": "Mobula nei",
        "name_es": "NA",
        "name_fr": "NA",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",  # some species are VU
        "iucn_population": "decreasing",
        "group": "ray",
        "group_subcategory": "ray",
    },
    "RRU": {
        "identifier": 3122,
        "scientific_name": "Elagatis bipinnulata",
        "name_en": "Rainbow runner",
        "name_es": "Macarela salmón",
        "name_fr": "Comète saumon",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Rainbow runner",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "RSK": {
        "identifier": 2806,
        "scientific_name": "Carcharhinidae",
        "name_en": "Requiem sharks nei",
        "name_es": "Cazones picudos,tintoreras nep",
        "name_fr": "Requins nca",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "shark",
        "group_subcategory": "shark",
    },
    "SFA": {
        "identifier": 3301,
        "scientific_name": "Istiophorus platypterus",
        "name_en": "Indo-Pacific sailfish",
        "name_es": "Pez vela del Indo-Pacífico",
        "name_fr": "Voilier indo-pacifique",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Indo pacific sailfish",
        "label2_fishnet": "BILL",
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "fish-other",
    },
    "SKH": {
        "identifier": 3387,
        "scientific_name": "Selachimorpha (Pleurotremata)",
        "name_en": "Various sharks nei",
        "name_es": "Escualos diversos nep",
        "name_fr": "Requins divers nca",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "shark",
        "group_subcategory": "shark",
    },
    "SKJ": {
        "identifier": 2494,
        "scientific_name": "Katsuwonus pelamis",
        "name_en": "Skipjack tuna",
        "name_es": "Listado",
        "name_fr": "Listao",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Skipjack tuna",
        "label2_fishnet": "SKJ",
        "iucn_category": "LC",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "SMA": {
        "identifier": 2011,
        "scientific_name": "Isurus oxyrinchus",
        "name_en": "Shortfin mako",
        "name_es": "Marrajo dientuso",
        "name_fr": "Taupe bleue",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "SPJ": {
        "identifier": 2823,
        "scientific_name": "Sphyrna tiburo",
        "name_en": "Bonnethead",
        "name_es": "Cornuda de corona",
        "name_fr": "Requin-marteau tiburo",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-illegal",
    },
    "SPK": {
        "identifier": 2824,
        "scientific_name": "Sphyrna mokarran",
        "name_en": "Great hammerhead",
        "name_es": "Cornuda gigante",
        "name_fr": "Grand requin marteau",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "CR",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "SPL": {
        "identifier": 2028,
        "scientific_name": "Sphyrna lewini",
        "name_en": "Scalloped hammerhead",
        "name_es": "Cornuda común",
        "name_fr": "Requin-marteau halicorne",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "CR",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "SPN": {
        "identifier": 2821,
        "scientific_name": "Sphyrna spp",
        "name_en": "Hammerhead sharks nei",
        "name_es": "Cornudas(=Peces martillo) nep",
        "name_fr": "Requins marteau nca",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "CR",  # some species are EN or VU
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "SPY": {
        "identifier": 2027,
        "scientific_name": "Sphyrnidae",
        "name_en": "Hammerhead sharks, etc. nei",
        "name_es": "Cornudas, etc. nep",
        "name_fr": "Requins marteau, etc. nca",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "shark",
        "group_subcategory": "shark",
    },
    "SPZ": {
        "identifier": 2822,
        "scientific_name": "Sphyrna zygaena",
        "name_en": "Smooth hammerhead",
        "name_es": "Cornuda cruz(=Pez martillo)",
        "name_fr": "Requin-marteau commun",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-illegal",
    },
    "SSP": {
        "identifier": 2502,
        "scientific_name": "Tetrapturus angustirostris",
        "name_en": "Shortbill spearfish",
        "name_es": "Marlín trompa corta",
        "name_fr": "Makaire à rostre court",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Shortbill spearfish",
        "label2_fishnet": "BILL",
        "iucn_category": "DD",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "SWO": {
        "identifier": 2503,
        "scientific_name": "Xiphias gladius",
        "name_en": "Swordfish",
        "name_es": "Pez espada",
        "name_fr": "Espadon",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Swordfish",
        "label2_fishnet": "BILL",
        "iucn_category": "NT",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "swordfish",
    },
    "THR": {
        "identifier": 2007,
        "scientific_name": "Alopias spp",
        "name_en": "Thresher sharks nei",
        "name_es": "Zorros nep",
        "name_fr": "Renards de mer nca",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",  # some species are VU
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "TIG": {
        "identifier": 2818,
        "scientific_name": "Galeocerdo cuvier",
        "name_en": "Tiger shark",
        "name_es": "Tintorera tigre",
        "name_fr": "Requin tigre commun",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "NT",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark-other",
    },
    "TRB": {
        "identifier": 15796,
        "scientific_name": "Triaenodon obesus",
        "name_en": "Whitetip reef shark",
        "name_es": "Tiburón coralero ñato",
        "name_fr": "Requin corail",
        "isscaap_group": "Sharks, rays, chimaeras",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "VU",
        "iucn_population": "decreasing",
        "group": "shark",
        "group_subcategory": "shark",
    },
    "TRQ": {
        "identifier": 16082,
        "scientific_name": "Trachipterus trachypterus",
        "name_en": "Mediterranean dealfish",
        "name_es": "Traquíptero",
        "name_fr": "Poisson ruban",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "unknown",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "TST": {
        "identifier": 15600,
        "scientific_name": "Taractichthys steindachneri",
        "name_en": "Sickle pomfret",
        "name_es": "Tristón segador",
        "name_fr": "NA",
        "isscaap_group": "Miscellaneous pelagic fishes",
        "label1_fishnet": "Sickle pomfret",
        "label2_fishnet": "OTH",
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "TUN": {
        "identifier": 2470,
        "scientific_name": "Thunnini",
        "name_en": "Tunas nei",
        "name_es": "Atunes nep",
        "name_fr": "Thonidés nca",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "TUS": {
        "identifier": 3295,
        "scientific_name": "Thunnus spp",
        "name_en": "True tunas nei",
        "name_es": "Atunes verdaderos nep",
        "name_fr": "Thons Thunnus nca",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "WAH": {
        "identifier": 3279,
        "scientific_name": "Acanthocybium solandri",
        "name_en": "Wahoo",
        "name_es": "Peto",
        "name_fr": "Thazard-bâtard",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Wahoo",
        "label2_fishnet": "OTH",
        "iucn_category": "LC",
        "iucn_population": "stable",
        "group": "fish",
        "group_subcategory": "fish-other",
    },
    "WHH": {
        "identifier": 19324,
        "scientific_name": "Tetrapturus spp",
        "name_en": "Spearfishes nei",
        "name_es": "Marlines Tetrapturus nep",
        "name_fr": "Makaires Tetrapturus nca",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": "fish",
        "group_subcategory": "fish",
    },
    "WHM": {
        "identifier": 3305,
        "scientific_name": "Kajikia albida",
        "name_en": "Atlantic white marlin",
        "name_es": "Aguja blanca del Atlántico",
        "name_fr": "Makaire blanc de l'Atlantique",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "LC",
        "iucn_population": "increasing",
        "group": "fish",
        "group_subcategory": "fish",
    },
    "YFT": {
        "identifier": 2497,
        "scientific_name": "Thunnus albacares",
        "name_en": "Yellowfin tuna",
        "name_es": "Rabil",
        "name_fr": "Albacore",
        "isscaap_group": "Tunas, bonitos, billfishes",
        "label1_fishnet": "Yellowfin tuna",
        "label2_fishnet": "YFT",
        "iucn_category": "LC",
        "iucn_population": "decreasing",
        "group": "fish",
        "group_subcategory": "tuna",
    },
    "DBZ": {
        "identifier": 30000,
        "scientific_name": "Tursiops aduncus",
        "name_en": "Indo-Pacific bottlenose dolphin",
        "name_es": "Delfín mular del Indo-Pacífico",
        "name_fr": "Grand dauphin de l'Indo-Pacifique",
        "isscaap_group": "Marine mammals",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "NT",
        "iucn_population": "unknown",
        "group": "mammal",
        "group_subcategory": "mammal",
    },
    "TTX": {
        "identifier": 30001,
        "scientific_name": "Testudinata",
        "name_en": "Turtles and shelled relatives",
        "name_es": "Tortugas y parientes con caparazón",
        "name_fr": "Tortues et leurs proches à carapace",
        "isscaap_group": "Reptiles",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "CR",
        "iucn_population": "decreasing",
        "group": "turtle",
        "group_subcategory": "turtle",
    },
    "XXX": {
        "identifier": 30002,
        "scientific_name": "Indeterminated",
        "name_en": None,
        "name_es": None,
        "name_fr": None,
        "isscaap_group": None,
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": None,
        "iucn_population": None,
        "group": None,
        "group_subcategory": None,
    },
    "TUG": {
        "identifier": 30003,
        "scientific_name": "Chelonia mydas",
        "name_en": "Green sea turtle",
        "name_es": "Tortuga verde",
        "name_fr": "Tortue verte",
        "isscaap_group": "Reptiles",
        "label1_fishnet": None,
        "label2_fishnet": None,
        "iucn_category": "EN",
        "iucn_population": "decreasing",
        "group": "turtle",
        "group_subcategory": "turtle",
    },
}

IUCN_ORDER = ["CR", "EN", "VU", "NT", "LC", "DD", "NE"]

ILLEGAL_SPECIES = [
    "OCS",
    "SPJ",
    "SPL",
    "SPZ",
    "SPK",
    "MAN",
    "PLS",
    "SPN",
    "SPY",
    "RMV",
    "TTX",
    "TUG",
    "FAL",
]

FISH_MAPPING_FILTERED = {
    class_name: fish_class
    for class_name, fish_class in FISH_MAPPING.items()
    if class_name
    not in [
        "PLS",
        "DOL",
        "YFT",
        "RMV",
        "MAN",
        "SFA",
        "SWO",
        "SPK",
        "SPN",
        "SPY",
        "SPZ",
        "BTH",
        "PTH",
        "THR",
        "BUM",
    ]
}

ICON_MAPPING = {
    1: {
        "CATCH": "fish.png",
    },
    2: {
        "FISH": "fish.png",
        "SHARK": "shark.png",
        "RAY": "ray.png",
        "TURTLE": "turtle.png",
        "MAMMAL": "mammal.png",
    },
    3: {
        "PLS": "stingray.png",
        "DOL": "dolphinfish.png",
        "YFT": "yellowfin_tuna.png",
        "SWO": "swordfish.png",
        **dict.fromkeys(["MAN", "RMV"], "manta_ray.png"),
        **dict.fromkeys(["SPK", "SPN", "SPY", "SPZ"], "hammerhead_shark.png"),
        **dict.fromkeys(["BUM", "SFA"], "sailfish.png"),
        **dict.fromkeys(["BTH", "PTH", "THR"], "thresher_shark.png"),
        **{
            class_name: f"{str(FISH_MAPPING_FILTERED[class_name]['group']).lower() + '.png' if FISH_MAPPING_FILTERED[class_name]['group'] is not None else 'fish.png'}"
            for class_name in FISH_MAPPING_FILTERED
        },
    },
}
